dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "./frontend/node_modules/"
script:
- mvn clean test
- npm run build --prefix frontend/
- sonar-scanner
before_script:
- npm install --prefix frontend/
after_success:
- mvn clean test jacoco:report coveralls:report
addons:
  sonarcloud:
    organization: bazhanel-github
    token: 87626d0afa64a156d0679d627f626d1da347c2bf
